name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Help us understand your use case.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: As a developer using Claude Code, I need to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches did you consider?

  - type: dropdown
    id: phase
    attributes:
      label: Relevant Phase
      description: Which project phase does this relate to?
      options:
        - Phase 1 - Core MCP + Vector Search
        - Phase 2 - Code Intelligence + Local Files
        - Phase 3 - Multi-Instance + Azure DevOps
        - Phase 4 - Graph Relationships + Automation
        - Future/Unknown
    validations:
      required: true

  - type: checkboxes
    id: checklist
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I searched existing issues and this is not a duplicate
          required: true
        - label: This aligns with the project's goals and architecture
          required: true
